"""empty message

Revision ID: 81017c5886c9
Revises: c281cfa41bb0
Create Date: 2018-03-21 17:50:36.783958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81017c5886c9'
down_revision = 'c281cfa41bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('data', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'data')
    # ### end Alembic commands ###
