"""empty message

Revision ID: c281cfa41bb0
Revises: 345e94e4eea1
Create Date: 2018-03-14 16:43:26.071095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c281cfa41bb0'
down_revision = '345e94e4eea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'photo')
    # ### end Alembic commands ###
